# Generated by Django 3.0.5 on 2020-04-17 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('difficult', models.IntegerField(default=1)),
                ('preparationTime', models.IntegerField(blank=True, null=True)),
                ('shortDiscription', models.TextField(default='')),
                ('description', models.TextField(default='')),
                ('photo', models.ImageField(blank=True, upload_to='images')),
                ('movie', models.CharField(blank=True, max_length=256, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='smaki.Category')),
            ],
            options={
                'verbose_name_plural': 'Dishes',
            },
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name_plural': 'Ingredients',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(blank=True, choices=[('Gr', 'Gr'), ('Ml', 'Ml'), ('Kg', 'Kg')], max_length=128, null=True)),
                ('quantity', models.CharField(blank=True, max_length=128, null=True)),
                ('dish', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='smaki.Dish')),
                ('ingredients', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='smaki.Ingredients')),
            ],
        ),
        migrations.AddField(
            model_name='dish',
            name='ingredients',
            field=models.ManyToManyField(through='smaki.Unit', to='smaki.Ingredients'),
        ),
    ]
