# Generated by Django 3.0.4 on 2020-04-15 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('quantity', models.IntegerField()),
                ('unit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='smaki.Unit')),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('difficult', models.IntegerField(default=1)),
                ('preparationTime', models.IntegerField(blank=True, null=True)),
                ('shortDiscription', models.TextField(default='')),
                ('description', models.TextField(default='')),
                ('photo', models.ImageField(blank=True, upload_to='images')),
                ('movie', models.CharField(blank=True, max_length=256, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='smaki.Category')),
                ('ingredients', models.ManyToManyField(to='smaki.Ingredients')),
            ],
        ),
    ]
